### ISSUE TITLE
edit email after schedualing

### ISSUE THREAD

**Issue by cryoguy** [bandresen/mu4e-send-delay#14]
long waited feature, thanks! A few questions:
Can I set delay with 3d, 1w etc? 
I can not seems to edit the emails after scheduling. any hits?
Another question is how to send the email right away? set the X-delay to 0min?

**Comment by bennyandresen** [comment]
> Can I set delay with 3d, 1w etc?
yeah, if you do that you can go to the drafts or check the minibuffer for the resulting date

> I can not seems to edit the emails after scheduling. any hits?
just entering the regular edit mode when you access drafts via mu4e should work

> Another question is how to send the email right away? set the X-delay to 0min?
if you pass a universal argument (C-u C-c C-c) then it will be sent instantly
